name: Currently reading books from Goodreads
on:
  schedule:
    - cron: "0 0 * * 0" # Run workflow at 00:00 every Sunday
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what I'm currently reading from GoodReads
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "33505127"
          shelf: "currently-reading"
